# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# Tails: The Amnesic Incognito Live System
# Copyright © 2012 Tails developers <tails@boum.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Monkey-patched Vagrant!
$:.unshift File.expand_path('../lib', __FILE__)
require 'vagrant_verified_download'
require 'tails_build_settings'

Vagrant.configure("2") do |config|
  config.vm.box = "tails-builder"
  config.vm.box_url = 'http://dl.amnesia.boum.org/tails/project/vagrant/squeeze-libvirt-v1.box'
  config.vm.box_checksum = '33c57cb4784abf1b8508c64f9e32456e237a7b346b393a40cfa64a6ae65e5433'
  config.vm.provision :shell, :inline => "http_proxy='#{ENV['http_proxy']}' /vagrant/provision/setup-tails-builder"

  config.vm.provider :libvirt do |libvirt|
    libvirt.driver = "qemu"
    libvirt.storage_pool_name = "default"
    if ENV['TAILS_RAM_BUILD']
      libvirt.memory = VM_MEMORY_FOR_RAM_BUILDS.to_i
    else
      libvirt.memory = VM_MEMORY_FOR_DISK_BUILDS.to_i
    end
    libvirt.cpus = ENV['TAILS_BUILD_CPUS'].to_i
  end
end
